### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by XenoAmess** [p-groarke/SDL_GameControllerDB2#5]
1. What is the reason for moving from gabomdq/SDL_GameControllerDB to p-groarke/SDL_GameControllerDB2 ?
2. Will the data format remain same?
3. What else is this SDL_GameControllerDB2 here different from original SDL_GameControllerDB that I should know as a user?

**Comment by p-groarke** [comment]
Hi @XenoAmess, thanks for the questions. I will leave this open a little while to make sure our users get to read this.

1. I could not get admin or ownership rights to the old repo, and I have plans that require them. For example, we have a nicer landing page already :) https://p-groarke.github.io/SDL_GameControllerDB2/ I can also manage collaborators (if need be) myself now.

2. Yes. Absolutely nothing changes to our day-to-day work.

3. Right now, it will mostly be repository related things. For ex, PRs now have a default message with better instructions. I will be doing the same for new issues to help newcomers etc. Not much will change in terms of what we do.

I hope this answers your questions and quells any worries you might have had.
Cheers

**Comment by XenoAmess** [comment]
got it...then I will move my related works to SDL_GameControllerDB2 too.
Thx.

**Comment by p-groarke** [comment]
No problem, thank you.

I'll reopen just in case others have the same questions (or new ones).

**Comment by p-groarke** [comment]
Oh and I forgot to mention the most important, please join me in welcoming @offalynne as an official collaborator! 🎉 

Offalynne has been helping a lot over the past years. Reviewing PRs, helping contributors and answering questions. All of this without once being asked to do so. It was quite time to say thank you and offer a sanctioned role in maintaining the db. :)

**Comment by XenoAmess** [comment]
Hey guys.
I notice that gabomdq/SDL_GameControllerDB has rebased and delete the out of maintain readme message.
Does that means you two repos are divided since now?
So I really wonders about how we users shall use the two repos... shall we merge the two db.txt files and then put them into our engines?

**Comment by p-groarke** [comment]
It seems the original owner has awaken from his slumber. He looks very angry.

Lets wait and see what he does. I don't want to hurt developers that rely on this db. So ultimately, I will do what is in there best interest. In the short term, I'll keep my fork up-to-date. But if he does a good job at maintaining the database, I won't compete with it.

**Comment by calexil** [comment]
no mention of the dmca takedown seems a little sus tbh

**Comment by harry-cpp** [comment]
If I am not mistaken, @p-groarke issued a DMCA takedown notice against SDL_GameControllerDB.

**Comment by p-groarke** [comment]
If you have questions, just ask. Since this is a legal matter, I am being more quiet than usual and may choose not answer everything.

Instead of explaining "my side of the story", I'll just say, I'm super sorry about this and the trouble it causes.

**Comment by flibitijibibo** [comment]
If you are actually sorry you will do one of three things, after which I will be willing to overlook all recent conduct:

1. Actually explain the commits outlined in the claim with the full context. As far as I am aware, the full license information including copyright owners was in LICENSE.
2. Revoke the claim and admit that it was a mistake (frankly, I don't care if it was even an honest one).
3. Don't get in my way when I re-host the original repository on my own accounts, with a commit log that shows that the owners are clearly listed and that any claims regarding removed copyrights are obviously false.

Under absolutely no circumstances can I or my users recommend even a third-party repository whose conduct could reflect this poorly on us or our products. Let me be 100% clear: This repo will never _ever_ be used by us.

**Comment by p-groarke** [comment]
https://github.com/FrodeSolheim/SDL_GameControllerDB/commit/9ab3461701a8e68ae2fbbe4231ab1dfa5ecbb2bd

https://github.com/FrodeSolheim/SDL_GameControllerDB/blame/master/check.py

> 3. This notice may not be removed or altered from any source distribution.

I don't know how clearer that can be tbh.

I understand you angry with me, since DMCA takedowns have a stigma. But you yourself contribute to an open-source repository, so you must understand how licenses and copyright work. They are at the center of what open-source is. How would you feel if someone grabbed your repo and stripped out the licenses?

Here are the options for the original author. He can reinstate the license, delete the python file and images or revert that file to before my rewrite. All are fine by me.

Like I said in this issue, I won't be competing with his repo. I had no idea he wanted to come back and work on it.

After 4 years of maintaining the db, including reviving it while the original author had left it to rot, I would have hoped a little good faith had developed.

**Comment by flibitijibibo** [comment]
DMCA have a stigma for a very good reason: They're almost exclusively used in bad faith.

There's one thing I think we can agree is true: You are not the author of SDL:

```
  Simple DirectMedia Layer
  Copyright (C) 2017-2018 Philippe Groarke <philippe.groarke@gmail.com>
```

Hypothetically, Sam could have done exactly the same thing, and yet he did not.

This could have been remedied with literally one patch to check.py with a standalone copyright notice like this one:

```
  check.py - Unit Testing Tool for SDL_GameControllerDB
  Copyright (C) 2017-2018 Philippe Groarke <philippe.groarke@gmail.com>
```

But trusting that Gabriel would have merged that in and admitted it was heavy-handed would have required "good faith", right?

**Comment by harry-cpp** [comment]
I am just gonna add that you should update your website, no game or engine use "your" db: https://p-groarke.github.io/SDL_GameControllerDB2/

**Comment by p-groarke** [comment]
No, I am absolutely not the author of the SDL and have never contributed to it.

In this case, I thought Simple DirectMedia Layer was referring to the license type. Yes that would work 100%.

If Gabriel absolutely wants to remove every mention of me in the repo, he can simply rewrite or revert the tests file. It's not a particularly complicated piece of code. There is no big issue here honestly. I just wont stand by while someone tries to take credit for my work.

BTW, I thought only the affected files would be taken down. For whatever that's worth. Github say they can't do that.

**Comment by flibitijibibo** [comment]
Oh no, the DMCA is suddenly causing trouble? Sounds like you really thought this through!

In any case, we have what we believe is the latest tip, so should you fail at undoing this mess, we will be rehosting this ourselves with the whopping 2-line fix. On the bright side, now a bunch of us definitely know you for something now!

**Comment by p-groarke** [comment]
You will also need to reinstate the copyright notice in the LICENSE file which covers the 2 images. Or you may delete the images and recreate them. 30 minutes in paint should do it.

I think regular contributors to the repo know me well enough. If you think removing licenses from other programmer's code is OK, I pity your collaborators.

**Comment by harry-cpp** [comment]
Instead of opening up an issue or a pr, you went for the DMCA... bravo...

**Comment by flibitijibibo** [comment]
This sure was a lot of work:

https://gist.github.com/flibitijibibo/529b8afccc181f83103d110eb9bbf1bb

I trust this would be enough to revoke the claim?

**Comment by p-groarke** [comment]
Yes absolutely. I will delete this fork once all of this is over.

You all seem to think the repo *had* to go down. It did not. Github DMCA notices give time to the author to make the necessary changes. All Gabriel had to do was revert the removal of the notices. The DMCA notice is the appropriate tool for such events.

You can read the DMCA notice, it is public.

> *What would be the best solution for the alleged infringement? Are there specific changes the other person can make other than removal? Can the repository be made private?*
> 
> The best solution would be the author reinstates the license and copyright notices he has removed.

**Comment by flibitijibibo** [comment]
I've sent the diff to Gabriel, if you want you can send him the same link as well to ensure he sees it. Be quick about it, I'd rather not have to re-host for no good reason.

**Comment by p-groarke** [comment]
I will.

If you do rehost, I have changes to `check.py` in this repo you might want as well. It removes the need to have SDL headers in the repo (it downloads the latest from their releases url).

**Comment by gabomdq** [comment]
There's nothing that can be done now, Github will take down the site for 10 days I believe and then bring it back up unless the person that filed the DMCA sues me (and all the fork owners?)...

Anyway, in the meantime there's a DMCA scrubbed repo at https://github.com/gabomdq/gamecontrollerdb (it's not 1:1 to the old repo because you know...I had to edit the check.py history), but I think you'll find the new check.py built from the ground up to be much better (a proper CI script will come in a few days)

**Comment by XenoAmess** [comment]
> There's nothing that can be done now, Github will take down the site for 10 days I believe and then bring it back up unless the person that filed the DMCA sues me (and all the fork owners?)...
> 
> Anyway, in the meantime there's a DMCA scrubbed repo at https://github.com/gabomdq/gamecontrollerdb (it's not 1:1 to the old repo because you know...I had to edit the check.py history), but I think you'll find the new check.py built from the ground up to be much better (a proper CI script will come in a few days)

Then you please make the CI script can detect whether the db.txt be well sorted.
I happened to see the db not sorted for several times.
You can just run your sort/formatted script in CI, and diff the result to the original db.txt, if not equal then fails.
DO NEVER think every committer MUST have been sorted it before they commit, there always be some rough guys.

**Comment by p-groarke** [comment]
Perfect, that settles it then.

Sorry for the inconvenience and best of luck with the db!
